### ISSUE TITLE
Docs show duplicate todo

### ISSUE THREAD

**Issue by Morriz** [PrefectHQ/marvin#630]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

When I visit https://www.askmarvin.ai/components/ai_application/ I see two exact same todo’s kept in the state, and afterticking one off it only updates the last one. Does this happen in the code as well? I presume the output was generated by code.

### Reproduction

```python3
Go to https://www.askmarvin.ai/components/ai_application/
```

### Versions

```Text
Not needed
```
