### ISSUE TITLE
Example not work

### ISSUE THREAD

**Issue by liebkne** [PrefectHQ/marvin#672]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to try to find a similar issue and didn't find one.
- [X] I searched the Marvin documentation for this issue.

### Bug summary

The example of AIApplication does not output desired results.

### Reproduction

```python3
Run the below code


from datetime import datetime

from marvin import AIApplication
from pydantic import BaseModel


# create models to represent the state of our ToDo app
class ToDo(BaseModel):
    title: str
    description: str = None
    due_date: datetime = None
    done: bool = False


class ToDoState(BaseModel):
    todos: list[ToDo] = []


# create the app with an initial state and description
todo_app = AIApplication(
    state=ToDoState(),
    description=(
        "A simple todo app. Users will provide instructions for creating and updating"
        " their todo lists."
    ),
)

# invoke the application by adding a todo
response = todo_app("I need to go to the store tomorrow at 5pm")


print(f"Response: {response.content}\n")
# Response: Got it! I've added a new task to your to-do list. You need to go to the store tomorrow at 5pm.


print(f"App state: {todo_app.state.model_dump_json(indent=2)}")
# App state: {
#   "todos": [
#     {
#       "title": "Go to the store",
#       "description": "Buy groceries",
#       "due_date": "2023-07-12T17:00:00+00:00",
#       "done": false
#     }
#   ]
# }

```

Outputs:

```
Response: Got it! I've added a note to remind you to go to the store tomorrow at 5pm. Is there anything else I can help you with?

App state: {
  "todos": []
}
```
```


### Error

```python3
No error
```

### Versions

```Text
Version:		1.5.6
Python version:		3.10.11
OS/Arch:		darwin/x86_64
```
```


### Additional context

_No response_

**Comment by zzstoatzz** [comment]
hi @liebkne - some things have changed since 1.5.6. you can find the updated example [here](https://www.askmarvin.ai/docs/interactive/applications/)

sorry about any confusion!
